package com.hllous.plantravel.ui.theme

import androidx.compose.ui.graphics.Color

// ── Atlas Light ────────────────────────────────────────────────
val AtlasLightPrimary               = Color(0xFF2563EB)
val AtlasLightOnPrimary             = Color(0xFFFFFFFF)
val AtlasLightPrimaryContainer      = Color(0xFFDBEAFE)
val AtlasLightOnPrimaryContainer    = Color(0xFF1E3A8A)
val AtlasLightSecondary             = Color(0xFF7C3AED)
val AtlasLightOnSecondary           = Color(0xFFFFFFFF)
val AtlasLightSecondaryContainer    = Color(0xFFEDE9FE)
val AtlasLightOnSecondaryContainer  = Color(0xFF4C1D95)
val AtlasLightTertiary              = Color(0xFFD97706)
val AtlasLightOnTertiary            = Color(0xFF451A03)
val AtlasLightTertiaryContainer     = Color(0xFFFEF3C7)
val AtlasLightOnTertiaryContainer   = Color(0xFF78350F)
val AtlasLightError                 = Color(0xFFB3261E)
val AtlasLightOnError               = Color(0xFFFFFFFF)
val AtlasLightErrorContainer        = Color(0xFFF9DEDC)
val AtlasLightOnErrorContainer      = Color(0xFF410E0B)
val AtlasLightBackground            = Color(0xFFF8FAFF)
val AtlasLightOnBackground          = Color(0xFF0F172A)
val AtlasLightSurface               = Color(0xFFFFFFFF)
val AtlasLightOnSurface             = Color(0xFF0F172A)
val AtlasLightSurfaceVariant        = Color(0xFFEDF1FB)
val AtlasLightOnSurfaceVariant      = Color(0xFF475569)
val AtlasLightOutline               = Color(0xFFC4CEDF)
val AtlasLightOutlineVariant        = Color(0xFFDDE3F0)
val AtlasLightInverseSurface        = Color(0xFF0F172A)
val AtlasLightInverseOnSurface      = Color(0xFFF1F0F4)
val AtlasLightInversePrimary        = Color(0xFF60A5FA)
val AtlasLightScrim                 = Color(0xFF000000)

// ── Atlas Dark ─────────────────────────────────────────────────
val AtlasDarkPrimary                = Color(0xFF60A5FA)
val AtlasDarkOnPrimary              = Color(0xFF0A1A3E)
val AtlasDarkPrimaryContainer       = Color(0xFF1E3A6E)
val AtlasDarkOnPrimaryContainer     = Color(0xFFBAD4FF)
val AtlasDarkSecondary              = Color(0xFFA78BFA)
val AtlasDarkOnSecondary            = Color(0xFF120027)
val AtlasDarkSecondaryContainer     = Color(0xFF3D1C8E)
val AtlasDarkOnSecondaryContainer   = Color(0xFFD4BBFF)
val AtlasDarkTertiary               = Color(0xFFFBB928)
val AtlasDarkOnTertiary             = Color(0xFF3A2200)
val AtlasDarkTertiaryContainer      = Color(0xFF3A2200)
val AtlasDarkOnTertiaryContainer    = Color(0xFFFFE08A)
val AtlasDarkError                  = Color(0xFFF2B8B5)
val AtlasDarkOnError                = Color(0xFF601410)
val AtlasDarkErrorContainer         = Color(0xFF8C1D18)
val AtlasDarkOnErrorContainer       = Color(0xFFF9DEDC)
val AtlasDarkBackground             = Color(0xFF0A0C14)
val AtlasDarkOnBackground           = Color(0xFFE2E8FF)
val AtlasDarkSurface                = Color(0xFF141A27)
val AtlasDarkOnSurface              = Color(0xFFE2E8FF)
val AtlasDarkSurfaceVariant         = Color(0xFF1E283E)
val AtlasDarkOnSurfaceVariant       = Color(0xFF8A9ABF)
val AtlasDarkOutline                = Color(0xFF384260)
val AtlasDarkOutlineVariant         = Color(0xFF2A3550)
val AtlasDarkInverseSurface         = Color(0xFFE2E8FF)
val AtlasDarkInverseOnSurface       = Color(0xFF1A1C1E)
val AtlasDarkInversePrimary         = Color(0xFF2563EB)
val AtlasDarkScrim                  = Color(0xFF000000)
