param(
    [Parameter(Mandatory = $true)]
    [string]$InputPath,

    [Parameter(Mandatory = $true)]
    [string]$OutputSqlPath,

    [string]$MappingPath = "app/src/main/resources/destinations/argentina_province_regions.csv",
    [string]$Admin1CodesPath = "C:\\tmp\\admin1CodesASCII.txt",
    [int]$MinimumPopulation = 1000
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Normalize-Text {
    param([string]$Value)

    $normalized = $Value.Normalize([Text.NormalizationForm]::FormD)
    $builder = [System.Text.StringBuilder]::new()

    foreach ($char in $normalized.ToCharArray()) {
        if ([Globalization.CharUnicodeInfo]::GetUnicodeCategory($char) -ne [Globalization.UnicodeCategory]::NonSpacingMark) {
            [void]$builder.Append($char)
        }
    }

    return $builder.ToString().ToLowerInvariant().Trim()
}

function Escape-SqlText {
    param([string]$Value)

    return $Value.Replace("'", "''")
}

$mapping = @{}
Import-Csv -Path $MappingPath | ForEach-Object {
    $mapping[(Normalize-Text $_.province)] = @{
        province = $_.province
        region = $_.region
    }
}

$admin1ToProvince = @{}
Get-Content -Path $Admin1CodesPath | ForEach-Object {
    $columns = $_ -split "`t"
    if ($columns.Length -lt 2) { return }
    if (-not $columns[0].StartsWith("AR.")) { return }
    $admin1ToProvince[$columns[0].Substring(3)] = $columns[1]
}

$seen = [System.Collections.Generic.HashSet[string]]::new()
$rows = New-Object System.Collections.Generic.List[string]

Get-Content -Path $InputPath -Encoding UTF8 | ForEach-Object {
    $columns = $_ -split "`t"
    if ($columns.Length -lt 15) { return }

    $sourceId = $columns[0]
    $name = $columns[1]
    $lat = $columns[4]
    $lng = $columns[5]
    $featureClass = $columns[6]
    $countryCode = $columns[8]
    $provinceCode = $columns[10]
    $population = 0
    [void][int]::TryParse($columns[14], [ref]$population)

    if ($featureClass -ne "P") { return }
    if ($countryCode -ne "AR") { return }
    if ($population -lt $MinimumPopulation) { return }
    if (-not $admin1ToProvince.ContainsKey($provinceCode)) { return }

    $provinceName = $admin1ToProvince[$provinceCode]
    $provinceKey = Normalize-Text $provinceName
    if (-not $mapping.ContainsKey($provinceKey)) { return }
    $province = $mapping[$provinceKey].province
    $region = $mapping[$provinceKey].region
    if (-not $seen.Add($sourceId)) { return }

    $normalizedName = Normalize-Text $name

    $rows.Add(
        "('geonames','$sourceId','$(Escape-SqlText $name)','$(Escape-SqlText $normalizedName)','$(Escape-SqlText $province)','$(Escape-SqlText $region)','$countryCode',$lat,$lng,$population,true)"
    ) | Out-Null
}

if ($rows.Count -eq 0) {
    throw "No destinations matched the import filters."
}

$sqlLines = New-Object System.Collections.Generic.List[string]
$sqlLines.Add("-- Generated by tools/destinations/import_geonames_argentina.ps1") | Out-Null

$batchSize = 500
for ($index = 0; $index -lt $rows.Count; $index += $batchSize) {
    $batch = $rows.GetRange($index, [Math]::Min($batchSize, $rows.Count - $index))
    $sqlLines.Add("insert into public.destinations (source, source_id, name, normalized_name, province, region, country_code, lat, lng, population, is_active)") | Out-Null
    $sqlLines.Add("values") | Out-Null
    $sqlLines.Add(($batch -join ",`n")) | Out-Null
    $sqlLines.Add("on conflict (source, source_id) do update set") | Out-Null
    $sqlLines.Add("  name = excluded.name,") | Out-Null
    $sqlLines.Add("  normalized_name = excluded.normalized_name,") | Out-Null
    $sqlLines.Add("  province = excluded.province,") | Out-Null
    $sqlLines.Add("  region = excluded.region,") | Out-Null
    $sqlLines.Add("  country_code = excluded.country_code,") | Out-Null
    $sqlLines.Add("  lat = excluded.lat,") | Out-Null
    $sqlLines.Add("  lng = excluded.lng,") | Out-Null
    $sqlLines.Add("  population = excluded.population,") | Out-Null
    $sqlLines.Add("  is_active = excluded.is_active,") | Out-Null
    $sqlLines.Add("  updated_at = now();") | Out-Null
    $sqlLines.Add("") | Out-Null
}

$directory = Split-Path -Parent $OutputSqlPath
if ($directory) {
    New-Item -ItemType Directory -Force -Path $directory | Out-Null
}

[System.IO.File]::WriteAllLines(
    $OutputSqlPath,
    $sqlLines,
    [System.Text.UTF8Encoding]::new($false)
)
Write-Host "Generated $($rows.Count) destination upserts at $OutputSqlPath"
